# Generated by Django 4.0.4 on 2022-07-07 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('adresse_postale', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('couleur', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('date_de_naissance', models.DateField()),
                ('matricule', models.CharField(max_length=10)),
                ('courriel', models.EmailField(max_length=254)),
                ('tel_fixe', models.CharField(max_length=20)),
                ('tel_mobile', models.CharField(max_length=20)),
                ('mot_de_passe', models.CharField(max_length=32)),
                ('amis', models.ManyToManyField(null=True, to='Trombo.personne')),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trombo.faculte')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_de_publication', models.DateField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trombo.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Trombo.personne')),
                ('annee', models.IntegerField()),
                ('cursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trombo.cursus')),
            ],
            bases=('Trombo.personne',),
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Trombo.personne')),
                ('bureau', models.CharField(max_length=30)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trombo.campus')),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trombo.fonction')),
            ],
            bases=('Trombo.personne',),
        ),
    ]
